all:
	gcc -I/home/fashion/project/hyperscan/build/install/include -L/root/hyperscan/lib/  -lasan -fsanitize=address -fno-omit-frame-pointer -lhs -g hyperscan.c -o hyperscan
	gcc -I/home/fashion/project/hyperscan/build/install/include -L/root/hyperscan/lib/  -lasan -fsanitize=address -fno-omit-frame-pointer -lhs -g hyperscan_example.c -o hyperscan_example
