all:
	gcc -lip4tc fake_iptables.c -o fake_iptables
	gcc -lip4tc get_chain.c -o get_chain
	# gcc -lip4tc get_rule.c -o get_rule
	# gcc -lip4tc create_chain.c -o create_chain
	# gcc -lip4tc create_rule.c -o create_rule
	