all:
	gcc -g pcap_block_sniffier.c -o pcap_block_sniffier -lpcap
	gcc -g pcap_nonblock_sniffier.c -o pcap_nonblock_sniffier -lpcap
	gcc -g pcap_filter.c -o pcap_filter -lpcap
clean:
	rm -rf pcap_block_sniffier pcap_nonblock_sniffier
